- name: disabling redis default module
  ansible.builtin.command: dnf module disable redis -y

- name: enabiling redis
  ansible.builtin.command: dnf module enable redis:7 -y

- name: installing redis
  ansible.builtin.package:
    name: redis
    state: installed

- name: changing ip to allow
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: disabling protected module
  ansible.builtin.lineinfile:
    path : /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: enabiling service for redis
  ansible.builtin.service:
    name: redis
    enabled: yes
    state: started