- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    sest: /etc/yum.repos.d/mongo.repo

- name: installing mongo server
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: allow all remote connections
  ansible.builtin.replace:
    path: /etc/mongo.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted
