- name: app setup
  include_role:
    name: common
    tasks_from: app_setup

- name: python setup
  include_role:
    name: common
    tasks_from: python

- name: systemd_service
  include_role:
    name: common
    tasks_from: systemd


