- name: nginx setup
  include_role:
    name: common
    tasks_from: nginx_setup

- name: removing default html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: adding the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: removing default html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: adding the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: downloading frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extracting frontend code
  ansible.builtin.unarchive:
    src:  /tmp/frontend.zip
    dest: /usr/share/nginx/html 
    remote_src: yes

- name: removing default nginx conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copying the nginx conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx


  