- name: nginx setup
  include_role:
    name: common
    tasks_from: nginx_setup

- name: removing default html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: adding the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: nginx setup
  include_role:
    name: common
    tasks_from: app_setup

- name: removing default nginx conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copying the nginx conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx


  